// French book names (KJF) keyed by slug — used to localize the copied reference.
export const FR_BOOKS: Record<string, string> = {
  genesis: 'Genèse',
  exodus: 'Exode',
  leviticus: 'Lévitique',
  numbers: 'Nombres',
  deuteronomy: 'Deutéronome',
  joshua: 'Josué',
  judges: 'Juges',
  ruth: 'Ruth',
  '1-samuel': '1 Samuel',
  '2-samuel': '2 Samuel',
  '1-kings': '1 Rois',
  '2-kings': '2 Rois',
  '1-chronicles': '1 Chroniques',
  '2-chronicles': '2 Chroniques',
  ezra: 'Esdras',
  nehemiah: 'Néhémie',
  esther: 'Esther',
  job: 'Job',
  psalms: 'Psaumes',
  proverbs: 'Proverbes',
  ecclesiastes: 'Ecclésiaste',
  'song-of-solomon': 'Cantique des Cantiques',
  isaiah: 'Ésaïe',
  jeremiah: 'Jérémie',
  lamentations: 'Lamentations',
  ezekiel: 'Ézéchiel',
  daniel: 'Daniel',
  hosea: 'Osée',
  joel: 'Joël',
  amos: 'Amos',
  obadiah: 'Abdias',
  jonah: 'Jonas',
  micah: 'Michée',
  nahum: 'Nahum',
  habakkuk: 'Habacuc',
  zephaniah: 'Sophonie',
  haggai: 'Aggée',
  zechariah: 'Zacharie',
  malachi: 'Malachie',
  matthew: 'Matthieu',
  mark: 'Marc',
  luke: 'Luc',
  john: 'Jean',
  acts: 'Actes',
  romans: 'Romains',
  '1-corinthians': '1 Corinthiens',
  '2-corinthians': '2 Corinthiens',
  galatians: 'Galates',
  ephesians: 'Éphésiens',
  philippians: 'Philippiens',
  colossians: 'Colossiens',
  '1-thessalonians': '1 Thessaloniciens',
  '2-thessalonians': '2 Thessaloniciens',
  '1-timothy': '1 Timothée',
  '2-timothy': '2 Timothée',
  titus: 'Tite',
  philemon: 'Philémon',
  hebrews: 'Hébreux',
  james: 'Jacques',
  '1-peter': '1 Pierre',
  '2-peter': '2 Pierre',
  '1-john': '1 Jean',
  '2-john': '2 Jean',
  '3-john': '3 Jean',
  jude: 'Jude',
  revelation: 'Apocalypse',
}
