// The single source of truth for which editions exist and how each behaves.
//
// Ids double as URL segments (#/john/3/en/16), localStorage keys for highlights,
// and data directories (public/data/<id>/). The original three keep their plain
// language codes so links shared before this change, and every saved annotation,
// still resolve.

/** The editions that ship with the app. */
export type BuiltinLang =
  | 'en' | 'ja' | 'jako' | 'fr' | 'zht' | 'zhs' | 'pt' | 'es' | 'ar' | 'tl' | 'el' | 'he' | 'eo' | 'la'

/**
 * An edition id.
 *
 * Open, not a closed union, because a reader can add their own: an imported edition's
 * id cannot be known here. `(string & {})` is the idiom that keeps the built-in
 * literals in autocompletion while admitting any string, so `BY_ID.en` still resolves
 * and every existing call site type-checks unchanged.
 *
 * The cost is that a mistyped literal is no longer a compile error, so ids that come
 * from outside the app — a URL hash, saved preferences, an invite link — are passed
 * through `isLang` at the boundary rather than trusted. That check is a real runtime
 * lookup in `BY_ID`, which is the merged registry below.
 */
export type Lang = BuiltinLang | (string & {})

/** How a verse's stored text is marked up — drives tokenizing in format.tsx. */
export type Markup =
  | 'kjv' // {supplied words} rendered italic
  | 'ruby' // {{漢字|かな}} furigana
  | 'plain'

/** Which half of the canon an edition actually contains. */
export type Coverage = 'all' | 'ot' | 'nt'

export interface VersionMeta {
  id: Lang
  /** Native language name, shown in the version picker and language ring. */
  label: string
  /** Short edition name — the badge under the label. */
  edition: string
  /** Full edition name, used when citing a copied verse. */
  fullName: string
  htmlLang: string
  dir: 'ltr' | 'rtl'
  /** BCP47 tag handed to the Web Speech API. */
  speech: string
  markup: Markup
  coverage: Coverage
  /** Visible for a first-time reader. Everything added later is opt-in. */
  defaultOn: boolean
  /** Whether this edition also supplies translated application chrome. */
  uiAvailable?: boolean
  /** Attribution line for the footer. */
  attribution: string
}

export const VERSIONS: VersionMeta[] = [
  {
    id: 'en',
    label: 'English',
    edition: 'KJV',
    fullName: 'King James Version (KJV)',
    htmlLang: 'en',
    dir: 'ltr',
    speech: 'en-US',
    markup: 'kjv',
    coverage: 'all',
    defaultOn: true,
    attribution: 'English: King James Version (1611), public domain',
  },
  {
    id: 'ja',
    label: '日本語',
    edition: '文語訳',
    fullName: '文語訳聖書',
    htmlLang: 'ja',
    dir: 'ltr',
    speech: 'ja-JP',
    markup: 'ruby',
    coverage: 'all',
    defaultOn: true,
    attribution: '日本語: 文語訳聖書 (明治元訳・大正改訳), public domain',
  },
  {
    id: 'jako',
    label: '日本語',
    edition: '口語訳',
    fullName: '口語訳聖書 (1954/1955)',
    htmlLang: 'ja',
    dir: 'ltr',
    speech: 'ja-JP',
    markup: 'ruby', // furigana generated by scripts/furigana-jako.mjs
    coverage: 'all',
    defaultOn: false,
    // getbible's japkougo is the only module of this edition in circulation and it
    // returns 18 chapters with no verses: Psalms 130-139, Proverbs 30-31,
    // Matthew 25-28, John 19, Romans 10. eBible carries no 口語訳, and the Japanese
    // Wikisource copy is a navigation stub under a copyright deletion request. Those
    // chapters show the coverage note instead of an empty column.
    attribution:
      '日本語: 口語訳聖書 (1954/1955), 日本聖書協会. パブリックドメイン (日本, 2006年). 米国での著作権状態は未確定 (see FUTURE.md). 底本に18章が欠落 (詩篇130-139, 箴言30-31, マタイ25-28, ヨハネ19, ローマ10).',
  },
  {
    id: 'fr',
    label: 'Français',
    edition: 'KJF',
    fullName: 'Bible King James Française (KJF)',
    htmlLang: 'fr',
    dir: 'ltr',
    speech: 'fr-FR',
    markup: 'plain',
    coverage: 'all',
    defaultOn: true,
    // The 2022 OSIS export this is built from has real gaps: 41 verses the KJV
    // carries are absent (15 in Revelation, 13 in Psalms, John 18:24, and a
    // scattering elsewhere). Those rows render the missing-verse placeholder,
    // stated rather than hidden. The Song of Solomon is no longer among them: the
    // export files it as Ecclesiastes 13-20, and repair-kjf.mjs moves it back.
    attribution:
      'Français: Bible King James Française © Nadine L. Stratford, reproduite sans modification. L\u2019export source omet 41 versets (dont Jean 18:24).',
  },
  {
    id: 'zht',
    label: '繁體中文',
    edition: '和合本',
    fullName: '新標點和合本',
    htmlLang: 'zh-Hant',
    dir: 'ltr',
    speech: 'zh-TW',
    markup: 'plain',
    coverage: 'all',
    defaultOn: false,
    attribution: '繁體中文: 新標點和合本 (1919), public domain',
  },
  {
    id: 'zhs',
    label: '简体中文',
    edition: '和合本',
    fullName: '新标点和合本',
    htmlLang: 'zh-Hans',
    dir: 'ltr',
    speech: 'zh-CN',
    markup: 'plain',
    coverage: 'all',
    defaultOn: false,
    attribution: '简体中文: 新标点和合本 (1919), public domain',
  },
  {
    id: 'pt',
    label: 'Português',
    edition: 'Almeida',
    fullName: 'João Ferreira de Almeida, Atualizada',
    htmlLang: 'pt',
    dir: 'ltr',
    speech: 'pt-BR',
    markup: 'plain',
    coverage: 'all',
    defaultOn: false,
    attribution: 'Português: João Ferreira de Almeida, Atualizada',
  },
  {
    id: 'es',
    label: 'Español',
    edition: 'RV1909',
    fullName: 'Reina-Valera 1909',
    htmlLang: 'es',
    dir: 'ltr',
    speech: 'es-ES',
    markup: 'kjv',
    coverage: 'all',
    defaultOn: false,
    attribution: 'Español: Reina-Valera (1909), public domain',
  },
  {
    id: 'ar',
    label: 'العربية',
    edition: 'فان دايك',
    fullName: 'ترجمة سميث وفان دايك',
    htmlLang: 'ar',
    dir: 'rtl',
    speech: 'ar-SA',
    markup: 'plain',
    coverage: 'all',
    defaultOn: false,
    attribution: 'العربية: ترجمة سميث وفان دايك (1865), public domain',
  },
  {
    id: 'tl',
    label: 'Tagalog',
    edition: 'ADB 1905',
    fullName: 'Ang Dating Biblia (1905)',
    htmlLang: 'tl',
    dir: 'ltr',
    speech: 'fil-PH',
    markup: 'plain',
    coverage: 'all',
    defaultOn: false,
    attribution: 'Tagalog: Ang Dating Biblia (1905), public domain',
  },
  {
    id: 'el',
    label: 'Ἑλληνική',
    edition: 'TR',
    fullName: 'Textus Receptus',
    htmlLang: 'grc',
    dir: 'ltr',
    speech: 'el-GR',
    markup: 'plain',
    coverage: 'nt',
    defaultOn: false,
    attribution: 'Ἑλληνική: Textus Receptus. New Testament only, public domain',
  },
  {
    id: 'he',
    label: 'עברית',
    edition: 'WLC',
    fullName: 'Westminster Leningrad Codex',
    htmlLang: 'hbo',
    dir: 'rtl',
    speech: 'he-IL',
    markup: 'plain',
    coverage: 'ot',
    defaultOn: false,
    // Measured against the KJV at build time: 137 of 929 Old Testament chapters
    // have a different verse count, because the Hebrew and English traditions draw
    // chapter boundaries differently (Numbers 16–17, Leviticus 5–6, Exodus 7–8 are
    // the well-known cases). Rows are matched by verse number, so in those chapters
    // the Hebrew column will not line up with the others. Stated rather than hidden.
    attribution:
      'עברית: Westminster Leningrad Codex. Old Testament only, public domain. Hebrew chapter and verse divisions differ from the English in roughly one OT chapter in seven, so parallel rows do not always correspond.',
  },
  {
    id: 'eo',
    label: 'Esperanto',
    edition: 'Londona Biblio',
    fullName: 'La Sankta Biblio (Londona Biblio, 1926)',
    htmlLang: 'eo',
    dir: 'ltr',
    speech: 'eo',
    markup: 'plain',
    coverage: 'all',
    defaultOn: false,
    uiAvailable: false,
    attribution:
      'Esperanto: La Sankta Biblio (Londona Biblio, 1926). Malnova Testamento tradukita de L. L. Zamenhof (1910); plena eldono de la Brita kaj Alilanda Biblia Societo. Public domain.',
  },
  {
    id: 'la',
    label: 'Latine',
    edition: 'Vulgata Clementina',
    fullName: 'Biblia Sacra Vulgata Clementina (1598)',
    htmlLang: 'la',
    dir: 'ltr',
    speech: 'la',
    markup: 'plain',
    coverage: 'all',
    defaultOn: false,
    uiAvailable: false,
    attribution:
      'Latine: Biblia Sacra Vulgata Clementina (1598), textus ex editione Migne 1880. The data shipped here is the 66-book cut taken before the reader could represent a deuterocanon; the source carries Tobit, Judith, Wisdom, Sirach, Baruch, the Maccabees and the continuations to Esther and Daniel, and `npm run fetch` now brings them through. Public domain; source: eBible.org latVUC.',
  },
]

/**
 * The live registry: the editions above, plus whatever the reader has imported.
 *
 * `BY_ID` is mutated in place rather than rebuilt, because it is imported by name all
 * over the app and a rebound module export would leave every holder looking at the
 * old object. The binding never changes; its contents do.
 *
 * `registerEditions` is called from `main.tsx` before the first render — synchronously,
 * off localStorage — because `BY_ID[lang].label` is on the path of nearly every
 * component and an edition arriving a tick later would render as a crash rather than
 * as a missing row.
 */
export const BY_ID = Object.fromEntries(VERSIONS.map((v) => [v.id, v])) as Record<Lang, VersionMeta>
export const VERSION_IDS: Lang[] = VERSIONS.map((v) => v.id)
export const DEFAULT_COLUMNS: Lang[] = VERSIONS.filter((v) => v.defaultOn).map((v) => v.id)

/** Every edition currently known, shipped first then imported in the order added. */
export const allVersions = (): VersionMeta[] => VERSION_IDS.map((id) => BY_ID[id])

/** Replace the imported half of the registry. Built-ins are never touched. */
export function registerEditions(imported: VersionMeta[]) {
  const builtin = new Set(VERSIONS.map((v) => v.id))
  for (const id of [...VERSION_IDS]) {
    if (builtin.has(id)) continue
    delete BY_ID[id]
    VERSION_IDS.splice(VERSION_IDS.indexOf(id), 1)
  }
  for (const v of imported) {
    if (builtin.has(v.id)) continue // a built-in id can never be taken over
    BY_ID[v.id] = v
    if (!VERSION_IDS.includes(v.id)) VERSION_IDS.push(v.id)
  }
}

/**
 * True for an id the registry actually knows — the guard at every boundary where an
 * id arrives from outside: a URL hash, a stored preference, an invite link.
 *
 * Deliberately a plain boolean and not a `x is Lang` type predicate. `Lang` now
 * admits any string, so a predicate would narrow the *failing* branch to `never` and
 * make the code after a rejected id unreachable as far as the compiler is concerned —
 * which is the opposite of what a guard is for.
 */
export const isLang = (x: unknown): boolean => typeof x === 'string' && x in BY_ID

/**
 * Whether this edition carries this book.
 *
 * Read off the book, not computed from the edition: `index.json` lists the editions
 * each book was actually built for, so this is exact where the old rule — the book's
 * position against a hard-coded 39 — was a coarse guess that could only describe a
 * canon of exactly 66 books in exactly two halves. It is also what lets an edition
 * carry the deuterocanon, or half of it, without a special case.
 *
 * `has` missing means an index.json from before the field existed, which an installed
 * app can be serving for one launch; assume the book is present rather than hiding
 * every column. `VersionMeta.coverage` stays as the editorial copy that *explains* an
 * absence ("This edition covers the New Testament only"), which is a different job.
 */
export const coversBook = (id: Lang, book?: { has?: Lang[] }) =>
  !book?.has ? true : book.has.includes(id)
